_target_: src.datamodules.parse_tranforms_config

augs: null
name: baseline
transforms:
  - _target_: albumentations.Normalize
    mean: 
      - 0.49139968
      - 0.48215827
      - 0.44653124
    std:
      - 0.24703233 
      - 0.24348505 
      - 0.26158768
  - _target_: albumentations.pytorch.ToTensorV2

