_target_: src.models.cifar_module.CIFARLitModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.1
  momentum: 0.9 
  weight_decay: 2e-4

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

scheduler: null

net:
  _target_: src.models.components.resnet.create_model
  model_name: ???
  num_channels: 3
  num_classes: 10
