_target_: core.experiment.LightningModel
net:
  _target_: core.experiment.parse_net_config
  model_name: resnet32

optimizer: 
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${dmt.trainer.max_epochs}