# @package _global_

defaults:
  - _self_
  - datamodule: mnist.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  - optional local: default.yaml

task_name: "eval"
run_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}

tags: ["dev"]

seed: ???

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
