defaults:
  - transforms: default.yaml

_target_: src.datamodules.mnist_datamodule.MNISTDataModule
data_dir: ${paths.data_dir}
batch_size: 128
train_val_test_split: [1000, 5_000, 64_000]
num_workers: 0
pin_memory: False